# Generated by Django 4.2.4 on 2023-11-17 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("architect_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "gem_locations",
                "unique_together": {("latitude", "longitude")},
            },
        ),
    ]
